# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: ["lts/*"]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: env load
        env:
          SUPER_SECRET: ${{ secrets.SUDO }}
      - run: npm i
      - name: building react
        run: npm run build
      - name: copy to nginx location
        run: cp -r build/* /var/www/test/
      - name: nginx restart
        run: echo $SUPER_SECRET | sudo -S systemctl restart nginx
